name: Set tag to version
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Extract version from file
        id: getversion
        run: |
          pkg_name="package.json"
          current_version=$(cat $pkg_name | grep '"version": "')
          new_tag=$(grep -Po '"[0-9]\.[0-9]\.[0-9]"' $current_version)
          echo "::set-output name=version::$new_tag"
      - name: Bump tag
        uses: mathieudutour/github-tag-action@v6.1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          custom_tag: ${{ steps.getversion.outputs.version }}