name: Bump Version
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Extract version from file
        id: getversion
        run: |
          echo "Start version check"
          pkg_name="package.json"
          new_tag=$(grep -Po '\d+\.\d+\.\d+' package.json)
          echo "::set-output name=version::$new_tag"
      - name: Bump tag
        uses: mathieudutour/github-tag-action@v6.1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          custom_tag: ${{ steps.getversion.outputs.version }}